DROP DATABASE IF EXISTS ToDoMk2;
CREATE DATABASE ToDoMk2;

USE ToDoMk2;

CREATE TABLE ToDo(
    ID INT NOT NULL AUTO_INCREMENT,
    Text NVARCHAR(255) NOT NULL,
    Category INT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE Entry(
    ID INT NOT NULL AUTO_INCREMENT,
    Text NVARCHAR(255) NOT NULL,
    Done BOOLEAN NOT NULL,
    LinkedToDo INT NULL,
    LinkedEntry INT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE Category(
    ID INT NOT NULL AUTO_INCREMENT,
    Name NVARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Authentication(
    Name NVARCHAR(255) NOT NULL,
    PassKey UUID NOT NULL DEFAULT UUID(),
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    PRIMARY KEY (Name)
);